name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: "Redmine ${{ matrix.redmine }} & Ruby ${{ matrix.ruby }}"
    strategy:
      fail-fast: false
      matrix:
        redmine:
          - "4.1-stable"
          - "4.2-stable"
        ruby:
          - "2.6"
          - "2.7"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: redmine/redmine
          ref: ${{ matrix.redmine }}
          path: redmine
      - uses: actions/checkout@v2
        with:
          path: redmine/plugins/common_mark
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libsqlite3-dev
      - name: Initialize Redmine
        run: |
          cd redmine
          cp \
            plugins/common_mark/config/database.yml.example \
            config/database.yml
          bundle install
          bin/rails db:create
          bin/rails generate_secret_token
          bin/rails db:migrate
          bin/rails redmine:load_default_data REDMINE_LANG=en
          bin/rails redmine:plugins:migrate
      - name: Run test
        run: |
          cd redmine
          RAILS_ENV=test bin/rails redmine:plugins:test
